name: memo_assistant
description: Logic designed for critical memorization tasks using principles from Anki and SuperMemo.
version: 1.0.0
homepage: https://t3infosec.com

environment:
  sdk: ^3.4.0

dependencies:
  fsrs: ^1.1.1
  hive: ^2.2.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  hive_test: ^1.0.1