// Mocks generated by Mockito 5.4.4 from annotations
// in memo_assistant/test/infrastructure/repositories/hive_memo_card_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:hive/hive.dart' as _i2;
import 'package:memo_assistant/src/infrastructure/data_sources/hive_memo_card_dta_source.dart'
    as _i3;
import 'package:memo_assistant/src/infrastructure/models/memo_card_dao.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBox_0<E> extends _i1.SmartFake implements _i2.Box<E> {
  _FakeBox_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HiveMemoCardDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveMemoCardDataSource extends _i1.Mock
    implements _i3.HiveMemoCardDataSource {
  MockHiveMemoCardDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Box<_i4.MemoCardDAO> get box => (super.noSuchMethod(
        Invocation.getter(#box),
        returnValue: _FakeBox_0<_i4.MemoCardDAO>(
          this,
          Invocation.getter(#box),
        ),
      ) as _i2.Box<_i4.MemoCardDAO>);

  @override
  _i5.Future<void> openBox() => (super.noSuchMethod(
        Invocation.method(
          #openBox,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addMemoCard(_i4.MemoCardDAO? card) => (super.noSuchMethod(
        Invocation.method(
          #addMemoCard,
          [card],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i4.MemoCardDAO?> getMemoCard(int? key) => (super.noSuchMethod(
        Invocation.method(
          #getMemoCard,
          [key],
        ),
        returnValue: _i5.Future<_i4.MemoCardDAO?>.value(),
      ) as _i5.Future<_i4.MemoCardDAO?>);

  @override
  List<_i4.MemoCardDAO> getAllMemoCards() => (super.noSuchMethod(
        Invocation.method(
          #getAllMemoCards,
          [],
        ),
        returnValue: <_i4.MemoCardDAO>[],
      ) as List<_i4.MemoCardDAO>);

  @override
  _i5.Future<void> deleteMemoCard(_i4.MemoCardDAO? card) => (super.noSuchMethod(
        Invocation.method(
          #deleteMemoCard,
          [card],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> closeBox() => (super.noSuchMethod(
        Invocation.method(
          #closeBox,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
